---
- name: Yum Install Docker and docker compose
  hosts: docker
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: latest
    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: latest
```